# Motor gráfico y rendimiento
backend = "glx";
vsync = true;
glx-no-stencil = false;
glx-no-rebind-pixmap = true;
use-damage = false;

# Bordes redondeados
corner-radius = 12;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# Desenfoque (Blur estilo cristal)
blur-method = "none";
blur-strength = 6;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;
blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Sombras
shadow = true;
shadow-radius = 15;
shadow-opacity = 0.5;
shadow-offset-x = -15;
shadow-offset-y = -15;

# Animaciones (Magia visual)
animations = true;
animation-stiffness = 200;
animation-window-mass = 0.5;
animation-dampening = 20;
animation-clamping = true;
animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-for-workspace-switch-in = "slide-down";
animation-for-workspace-switch-out = "zoom";

# Opacidad (Hacer la terminal transparente)
opacity-rule = [
  "90:class_g = 'xfce4-terminal'"
];
